<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
    <id>https://status.100up.org</id>
    <title>100UP Hosting Status</title>
    <updated>2021-03-13T13:30:05.445Z</updated>
    <generator>Statusfy</generator>
    <link rel="alternate" href="https://status.100up.org"/>
    <link rel="self" href="https://status.100up.org/feeds/incidents.en.atom"/>
    <subtitle>100UP Hosting Status Page</subtitle>
    <entry>
        <title type="html"><![CDATA[Canada Host 4 network issues]]></title>
        <id>https://status.100up.org/incidents/1a32b31e</id>
        <link href="https://status.100up.org/incidents/1a32b31e"/>
        <updated>2021-03-11T21:11:25.268Z</updated>
        <content type="html"><![CDATA[<div class="update-block">
          <div class="update-block-date">2021-03-12T12:11:25.268Z</div>
          <div class="update-block-content">
            <div class="update-block-title">Resolved</div>
            <div class="update-block-body">
<p>All services are online again. OVH confirmed that the server was inaccessible from the network due to a network issue.</p>
<p>Task was: <a href="http://travaux.ovh.net/?do=details&amp;id=49523" target="_blank" rel="noopener noreferrer" class="external">http://travaux.ovh.net/?do=details&amp;id=49523</a></p>
</div></div></div>
<div class="update-block">
          <div class="update-block-date">2021-03-11T21:11:25.268Z</div>
          <div class="update-block-content">
            <div class="update-block-title">Identified</div>
            <div class="update-block-body">
<p>Host 4 started to show significant packet loss. After a reboot, it does not come online again. Hard reboot times out. IPMI times out. An OVH technician is already working on the rack.</p>
</div></div></div>
]]></content>
    </entry>
    <entry>
        <title type="html"><![CDATA[Fire in Strasbourg, France Data Center]]></title>
        <id>https://status.100up.org/incidents/5495ef8d</id>
        <link href="https://status.100up.org/incidents/5495ef8d"/>
        <updated>2021-03-10T01:47:58.454Z</updated>
        <content type="html"><![CDATA[<div class="update-block">
          <div class="update-block-date">2021-03-12T20:11:25.268Z</div>
          <div class="update-block-content">
            <div class="update-block-title">Update</div>
            <div class="update-block-body">
<p>OVH will take several weeks or more to bring the services in Strasbourg online again.</p>
<p>We have ordered new servers in Roubaix to temporarily restore all affected customers servers there. Sadly there is also no ETA for deliveries in Roubaix, but it should be around 15th March.</p>
</div></div></div>
<div class="update-block">
          <div class="update-block-date">2021-03-10T01:47:58.454Z</div>
          <div class="update-block-content">
            <div class="update-block-title">Identified</div>
            <div class="update-block-body">
<p>OVH Announcement: We are currently facing a major incident in our DataCenter of Strasbourg. If your production is in Strasbourg, we recommend to activate your Disaster Recovery Plan.</p>
<p>Detailed information <a href="http://travaux.ovh.net/?do=details&amp;id=49484" target="_blank" rel="noopener noreferrer" class="external">http://travaux.ovh.net/?do=details&amp;id=49484</a></p>
</div></div></div>
<!--- language code: en -->
]]></content>
    </entry>
    <entry>
        <title type="html"><![CDATA[Reboot Host 5]]></title>
        <id>https://status.100up.org/incidents/4f20d413</id>
        <link href="https://status.100up.org/incidents/4f20d413"/>
        <updated>2019-12-21T03:42:36.690Z</updated>
        <content type="html"><![CDATA[<p>Reboot Host 5 to fix bugged cgroups.</p>
<!--- language code: en -->
]]></content>
    </entry>
</feed>